### ISSUE TITLE
easy to mis-operate twice or more when releasing new work

### ISSUE THREAD

**Issue by musicoj** [Musicoin/desktop#8] opened 2016-11-22 05:30 UTC
In the new version 0.0.8, when clicking the "release" button in "preview license", there's no progress or status visible to user. So it's easy to click twice or more to generate repeated licenses. 

![image](https://cloud.githubusercontent.com/assets/23398496/20512001/a62c9c9a-b0b7-11e6-8109-e92fe98b1dbf.png)

**Comment by musicoj** [comment] 2016-11-22 07:03
the result seems not so concerting, one contracted, another one no contract created but still listed. 

![image](https://cloud.githubusercontent.com/assets/23398496/20514038/c4bec87e-b0c4-11e6-81c0-03a077eb6ec7.png)

**Comment by phiferd** [comment] 2016-11-22 12:05
I will make the progress indicator less subtle and add some logic to prevent an accidental re-submission.

**Comment by phiferd** [comment] 2016-11-23 00:15
As for the license not showing up, the issue is that the Work contract was created but the PPP license contract was not.  I have seen this issue before, but I haven't been able to track it down.  I'm wondering if the local node submitted the transaction but it wasn't confirmed for some reason.

**Comment by immartian** [comment] 2016-11-23 00:16
We may need some amendment on where to place the license, after consulting to lawyer briefly. Will share in goals of next MVP.

**Comment by Varunram** [comment] 2017-09-08 12:50
Closing this for the time-being!

**Closed by Varunram** 2017-09-08 12:50 UTC
