### ISSUE TITLE
Wallet 1.0 imports the keystore file, computer resets before sync is done, new wallet loses account data and now keystore file is nowhere to be found. 

### ISSUE THREAD

**Issue by Passingby1** [Musicoin/desktop#167] opened 2018-02-17 05:12 UTC
Is there any other place where the new wallet stores account information?? 

0xbb0b5df0d1e0c1e7aae4fa749931f5395b8877ba

I know it is not much but it is frustrating as hell it will be lost, especially because for some reason the new wallet does not make an immediate backup of the keystore file it imported.

**Comment by Varunram** [comment] 2018-02-18 10:53
Could you provide more info regarding "computer reset"?

**Comment by cryptofuture** [comment] 2018-02-18 10:55
It always located at `\AppData\Roaming\Musicoin\keystore` folder under Windows, in `~./musicoin/keystore` under Linux and in `Username/Library/Musicoin/keystore` under macOS.
Same location is valid to the 0.7 and 0.8. 

In case you have some hardware issues, you should definitely looks on solving those first.

**Comment by Passingby1** [comment] 2018-02-18 12:15
> Could you provide more info regarding "computer reset"?

Of course, while the new wallet was syncing a newly made Windows 10 install decided to restart the computer. After booting to desktop again, I opened the new wallet , there was no trace of my Music address/account. It was then when I looked for the keystore file on the computer and realized the new wallet, instead of copying it, decided to **move** the file to the new location, where it was nowhere to be found. Tried to open the old wallet, of course, without a keyfile, when it opened it didn't have my account info either. 

A bug probably related to the wallet being unable to finish that first sync. My guess is, the wallet would've made a new keystore file after finishing that first sync. 

It is a very poor design decision to have the new wallet arbitrarily move/delete files without requesting for user input nor backing them up first, fact is, the keystore file was nowhere to be found anywhere on the computer. In this case a new 10 install decided to act on its own, it could've been a computer crash, electricity could've gone out at that moment, etc...

 As I said, it's no big deal, with the price Music currently has, lost like 10usd there. Just trying to make you aware that this shouldn't have happened if the new wallet didn't take upon itself to remove/move files, especially vital ones. 

> In case you have some hardware issues, you should definitely look on solving those first.

Awesome response, classy.

**Comment by cryptofuture** [comment] 2018-02-18 12:17
Keystore location is just the same:
```
\AppData\Roaming\Musicoin\keystore
```
for you.

**Comment by Varunram** [comment] 2018-02-18 13:05
> A bug probably related to the wallet being unable to finish that first sync. My guess is, the wallet would've made a new keystore file after finishing that first sync

The keystore is created on booting up the wallet, so that possibility is ruled out I guess.

> It is a very poor design decision to have the new wallet arbitrarily move/delete files without requesting for user input nor backing them up first, fact is, the keystore file was nowhere to be found anywhere on the computer

We don't move files around (especially the keystore) without asking for your explicit permission like with the backup functionality.

> As I said, it's no big deal, with the price Music currently has, lost like 10usd there. Just trying to make you aware that this shouldn't have happened if the new wallet didn't take upon itself to remove/move files, especially vital ones.

The monetary issue aside, there *might* be a problem with you hardware as cryptofuture suggested, which may be causing random deletion of memory. This is because we don't move around keystore file location unless you upgrade operating systems themselves (like XP->7 for e.g.). I'll try to reproduce this and report any erratic behaviour.

**Comment by cryptofuture** [comment] 2018-02-18 14:08
Keystore location might only change in very rare occasion on the Windows, in case your Windows (windows installation) system disk located not on `C:\\`, because before in the wallet it was harcoded to the disk `C:\\`. So in case like for ex. your Windows installed on disk `G:\\` keystore location might change.
But you could find it in the same path, but on disk `C:\\`

**Comment by Varunram** [comment] 2018-02-25 06:51
Any further questions on this or can I close?

**Comment by Varunram** [comment] 2018-03-30 06:59
Closing this.

**Closed by Varunram** 2018-03-30 06:59 UTC
Labels: bug
