### ISSUE TITLE
Move to Yarn

### ISSUE THREAD

**Issue by etaletai13** [Musicoin/desktop#224] opened 2018-04-05 21:49 UTC
### [dependencies] Bower: abandon ship; they did.
Bower's team has given up on maintaining it. So, it's on us to migrate away from it! Yarn is being used as the npm package manager from patch #216 ; so it only makes sense to migrate the bower workflow to yarn as well and remove a whole step.

### Checklist for contributions!
1. Pull down the current patch #216, and start there.
2. Add the bower deps as devDependency entries.
3. Point each one to the `@interface/bower_components` equivalent.
4. Run `yarn preview` to be sure nothing was broken.
5. If you're satisfied with your work, run 
`yarn contribute` and make a PR to https://github.com/etaletai13/desktop

### For test/review:
1. Pull the current state of patch #216.
2. Run `yarn preview`
3. Run `yarn test`
4. Consider adding tests to the scripts if you find yourself checking them each time manually.

**Comment by Varunram** [comment] 2018-04-06 12:40
Agreed, might be wiser to use yarn. We didn't use bower heavily, but using a maintained package is better, as you point out rightly in your issue post.

**Comment by etaletai13** [comment] 2018-04-06 14:35
@Varunram Bower is surprisingly not a hard thing to migrate from to Yarn. For now, I'm leaving bower in place and redundantly list the dependencies in the package.json. When its time to merge, that'll change. For now, "yarn prepare" should take care of things. I don't know about other OSs than OSX for the moment, but I'll handle that after this works.

**Comment by Varunram** [comment] 2018-04-21 12:51
Closed via https://github.com/Musicoin/desktop/commit/e34382b1953800c2225f79bfdbc613351714da97 but we won't be moving to yarn in our build system and here's why. Yarn took 30 minutes and still didn't come up with a build whereas we build all our assets on builder in 11 minutes. Attaching output below for ref:

```
real	28m6.646s
user	4m0.249s
sys	4m5.371s
```

@cryptofuture will be attaching the builder benchmarks shortly to provide a level comparison though, will wait until then.

**Comment by Varunram** [comment] 2018-04-21 15:57
@etaletai13 I can confirm that installing yarn takes up more than 1G in memory. This is due to many unrelated bower and npm modules (please check `bower.json` and `package.json`) to include only the modules which we sue and not the ones which are local to your system. If you can put in a PR with the changes, I'd be willing to accept it. I shall also send you a bounty of 3k MC soon after you put in the changes regarding yarn. 

Also, next time please don't delete the repo from which you issued the PR, makes it impossible for us to test before merge.

**Comment by etaletai13** [comment] 2018-04-21 16:37
I'm actually entirely rewriting quite a bit of this, and enough changes by it that it'll need to be 1.5.0. The method of directly converting is all well and good for effective end-user builds, but as you've said it pulls in a lot more than it needs to and I found that the end product is a bit huge. That said it's a lot more secure for many reasons. I'll write again when I've adapted the thing by hand, front-load the hard part right? If it doesn't out-match the build system in use, it could be still used in pieces for other reasons aplenty.

**Comment by etaletai13** [comment] 2018-04-30 17:07
Alright. So there could be plenty of reasons why your build didn't seem to work. I'll show this, and ask that you try out simply cloning etaletai13/desktop, and type nothing but "yarn" in the directory after cloning. For now, you'll need to npm install -G yarn first, but that'll be done in the package itself later if this is good for you. There is zero need for any of the build scripts at all, and the time to build gmc should be assumed - because shoving a binary in after the fact and hoping is a terrible method.
![screen shot 2018-04-30 at 10 03 45 am](https://user-images.githubusercontent.com/36354460/39439937-21b39362-4c5e-11e8-8cec-3e95334a3bd2.png)

As far as the repo deletion, I'll do that if 1. I don't want the PR being pulled at all, because I've gone another direction; or 2. It's been merged and I like a clean setup on my patching from my end. Tests are good and needed (note that the current Master branch actually doesn't build for this reason). I hope that made sense.

**Comment by Varunram** [comment] 2018-04-30 18:01
Thanks, wil test and review tomorrow!

**Comment by etaletai13** [comment] 2018-04-30 20:12
I hope you like it, and I think it'll open some doors for other helpers! :) †

**Closed** 2018-05-23 04:06 UTC
Labels: in-progress, release-1.5
